# Generated by Django 3.2 on 2021-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.fitmirchi.com%2F&psig=AOvVaw2nPjKdcIAJv-IQe0VdTu7M&ust=1619421893892000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMDu6-bumPACFQAAAAAdAAAAABAU', max_length=500),
        ),
    ]
