# Generated by Django 3.2 on 2021-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://fitmirchi.com/admin/assets/images/image_not_available.png', max_length=500),
        ),
    ]
